/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package penjualan.view;
import penjualan.entity.barang;
import penjualan.implement.barangImplement;
import penjualan.interfc.barangInterfc;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import pkgSIK_sipenjualan.FPenjualan;
/**
 * 985
 * @author student
 */
public final class barangView extends javax.swing.JFrame {
    List<barang> record = new ArrayList<>();
    barangInterfc brgServis;
    int row;
    /**
     * Creates new form barangView
     */
    public barangView() {
        initComponents();
        brgServis = new barangImplement();
        tabelBarang.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            row = tabelBarang.getSelectedRow();
            if(row!=-1){
                isiText();
            }
        });
        this.statusAwal();
    }
    
    void loadData(){
        try{
            record = brgServis.getAll();
        }
        catch(SQLException ex){
            Logger.getLogger(barangView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void isiTabel(){
        Object data[][] = new Object[record.size()][4];
        int x = 0;
        for(barang brg:record){
            data[x][0] = brg.getkodeBarang();
            data[x][1] = brg.getNamaBarang();
            data[x][2] = brg.getJumlah();
            data[x][3] = brg.getHarga();
            x++;
        }
            String judul[] = {"Kode Barang","Nama Barang","Jumlah","Harga"};
        tabelBarang.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(tabelBarang);
    }
    
    void kosongkanText(){
        kodeBarang.setText("");
        namaBarang.setText("");
        jumlah.setText("");
        harga.setText("");
    }
    
    void isiText(){
        barang brg = record.get(row);
        kodeBarang.setText(brg.getkodeBarang());
        namaBarang.setText(brg.getNamaBarang());
        jumlah.setText(brg.getJumlah()+ "");
        harga.setText(brg.getHarga()+ "");
    }
    
    void statusAwal(){
        kosongkanText();
        loadData();
        isiTabel();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kodeBarang = new javax.swing.JTextField();
        namaBarang = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        tambahBarang = new javax.swing.JButton();
        ubahBarang = new javax.swing.JButton();
        hapusBarang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        kembaliBtn = new javax.swing.JButton();

        setTitle("MASTER BARANG");

        jLabel1.setText("KODE BARANG");

        jLabel2.setText("NAMA BARANG");

        jLabel3.setText("JUMLAH");

        jLabel4.setText("HARGA");

        kodeBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        namaBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jumlah.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        harga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        tambahBarang.setText("TAMBAH");
        tambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBarangActionPerformed(evt);
            }
        });

        ubahBarang.setText("UBAH");
        ubahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahBarangActionPerformed(evt);
            }
        });

        hapusBarang.setText("HAPUS");
        hapusBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBarangActionPerformed(evt);
            }
        });

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Jumlah", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabelBarang);

        jButton1.setText("RESET FIELD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        kembaliBtn.setText("Kembali");
        kembaliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel3)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                            .addComponent(kodeBarang)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tambahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(ubahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(hapusBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(kembaliBtn)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBarang)
                    .addComponent(ubahBarang)
                    .addComponent(hapusBarang)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(kembaliBtn)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void tambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBarangActionPerformed
        // TODO add your handling code here:
        String cekkodeBarang = kodeBarang.getText();
        String ceknamaBarang = namaBarang.getText();
        String cekjumlah = jumlah.getText();
        String cekharga = harga.getText();
        
        if(cekkodeBarang.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Kode Barang belum di isi!");
        }else if(ceknamaBarang.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Barang belum di isi!");
        }else if(cekjumlah.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah belum di isi!");
        }else if(cekharga.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Harga belum di isi!");
        }else{
            try{
                barang brg = new barang();
                brg.setkodeBarang(kodeBarang.getText());
                brg.setNamaBarang(namaBarang.getText());
                brg.setJumlah(jumlah.getText());
                brg.setHarga(harga.getText());
                brgServis.insert(brg);
                        this.statusAwal();
                        JOptionPane.showMessageDialog(this, "Data barang berhasil disimpan!");
            }
            catch(SQLException ex){
                Logger.getLogger(barangView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_tambahBarangActionPerformed

    private void ubahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahBarangActionPerformed
        // TODO add your handling code here:
        String cekkodeBarang = kodeBarang.getText();
        
        if(cekkodeBarang.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih barang yang ingin diubah!");
        }else{
            try{
                barang brg = new barang();
                brg.setkodeBarang(kodeBarang.getText());
                brg.setNamaBarang(namaBarang.getText());
                brg.setJumlah(jumlah.getText());
                brg.setHarga(harga.getText());
                brgServis.update(brg);
                        this.statusAwal();
                        JOptionPane.showMessageDialog(this, "Data barang berhasil dirubah!");
            }
            catch(SQLException ex){
                Logger.getLogger(barangView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ubahBarangActionPerformed

    private void hapusBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBarangActionPerformed
        // TODO add your handling code here:
        String cekkodeBarang = kodeBarang.getText();
        
        if(cekkodeBarang.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih barang yang ingin dihapus!");
        }else{
            try{
                barang brg = new barang();
                String kode_barang = kodeBarang.getText();
                brgServis.delete(kode_barang);
                        this.statusAwal();
                        JOptionPane.showMessageDialog(this, "Data barang berhasil dihapus!");
            }
            catch(SQLException ex){
                Logger.getLogger(barangView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_hapusBarangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        kosongkanText();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void kembaliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBtnActionPerformed
        // TODO add your handling code here:
        new FPenjualan().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new barangView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapusBarang;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton kembaliBtn;
    private javax.swing.JTextField kodeBarang;
    private javax.swing.JTextField namaBarang;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JButton tambahBarang;
    private javax.swing.JButton ubahBarang;
    // End of variables declaration//GEN-END:variables
}
