/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package penjualan.view;
import penjualan.entity.pelanggan;
import penjualan.implement.pelangganImplement;
import penjualan.interfc.pelangganInterfc;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 * 985
 * @author Befril Renfiliani
 */
public final class pelangganView extends javax.swing.JFrame {
    List<pelanggan> record = new ArrayList<>();
    pelangganInterfc plgServis;
    int row;
    /**
     * Creates new form pelangganView
     */
    public pelangganView() {
        initComponents();
        plgServis = new pelangganImplement();
        tabelPelanggan.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            row = tabelPelanggan.getSelectedRow();
            if(row!=-1){
                isiText();
            }
        });
        this.statusAwal();
    }
    
    //Untuk load semua data dari tabel pelanggan
    void loadData(){
        try{
            record = plgServis.getAll();
        }
        catch(SQLException ex){
            Logger.getLogger(pelangganView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void isiTabel(){
        Object data[][] = new Object[record.size()][5];
        int x = 0;
        for(pelanggan plg:record){
            data[x][0] = plg.getkodePelanggan();
            data[x][1] = plg.getNamaPelanggan();
            data[x][2] = plg.getjenisKelamin();
            data[x][3] = plg.getAlamat();
            data[x][4] = plg.getTelp();
            x++;
        }
        String judul[] = {"Kode Pelanggan","Nama Pelanggan","Jenis Kelamin","Alamat","No. Telp"};
        tabelPelanggan.setModel(new DefaultTableModel(data, judul));
        jScrollPane1.setViewportView(tabelPelanggan);
    }
    
    void kosongkanText(){
        kodePelanggan.setText("");
        namaPelanggan.setText("");
        jenisKelamin.setSelectedItem("-= pilih =-");
        alamat.setText("");
        telp.setText("");
    }
    
    void isiText(){
        pelanggan plg = record.get(row);
        kodePelanggan.setText(plg.getkodePelanggan());
        namaPelanggan.setText(plg.getNamaPelanggan());
        jenisKelamin.setSelectedItem(plg.getjenisKelamin());
        alamat.setText(plg.getAlamat());
        telp.setText(plg.getTelp());
    }
    
    void statusAwal(){
        kosongkanText();
        loadData();
        isiTabel();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kodePelanggan = new javax.swing.JTextField();
        namaPelanggan = new javax.swing.JTextField();
        jenisKelamin = new javax.swing.JComboBox();
        telp = new javax.swing.JTextField();
        tambahPelanggan = new javax.swing.JButton();
        ubahPelanggan = new javax.swing.JButton();
        hapusPelanggan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();

        setTitle("MASTER PELANGGAN");

        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Pelanggan", "Nama Pelanggan", "Jenis Kelamin", "Alamat", "No. Telp"
            }
        ));
        jScrollPane1.setViewportView(tabelPelanggan);

        jLabel1.setText("KODE PELANGGAN");

        jLabel2.setText("NAMA PELANGGAN");

        jLabel3.setText("JENIS KELAMIN");

        jLabel4.setText("ALAMAT");

        jLabel5.setText("NO. TELP");

        jenisKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-= pilih =-", "pria", "wanita" }));

        tambahPelanggan.setText("TAMBAH");
        tambahPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPelangganActionPerformed(evt);
            }
        });

        ubahPelanggan.setText("UBAH");
        ubahPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahPelangganActionPerformed(evt);
            }
        });

        hapusPelanggan.setText("HAPUS");
        hapusPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPelangganActionPerformed(evt);
            }
        });

        jButton1.setText("RESET FIELD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane2.setViewportView(alamat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kodePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(ubahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(hapusPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kodePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(16, 16, 16)
                        .addComponent(namaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahPelanggan)
                    .addComponent(ubahPelanggan)
                    .addComponent(hapusPelanggan)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPelangganActionPerformed
        // TODO add your handling code here:
        String cekkodePelanggan = kodePelanggan.getText();
        String ceknamaPelanggan = namaPelanggan.getText();
        String cekjenisKelamin = (String) jenisKelamin.getSelectedItem();
        String cekalamat = alamat.getText();
        String cektelp = telp.getText();
        
        if(cekkodePelanggan.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Kode Pelanggan belum di isi!");
        }else if(ceknamaPelanggan.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama Pelanggan belum di isi!");
        }else if("-= pilih =-".equals(cekjenisKelamin)){
            JOptionPane.showMessageDialog(null, "Jenis Kelamin belum dipilih!");
        }else if(cekalamat.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Alamat belum di isi!");
        }else if(cektelp.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "No. Telp belum di isi!");
        }else{
            try{
                pelanggan plg = new pelanggan();
                plg.setkodePelanggan(kodePelanggan.getText());
                plg.setNamaPelanggan(namaPelanggan.getText());
                plg.setjenisKelamin((String) jenisKelamin.getSelectedItem());
                plg.setAlamat(alamat.getText());
                plg.setTelp(telp.getText());
                plgServis.insert(plg);
                this.statusAwal();
                JOptionPane.showMessageDialog(this, "Data pelanggan berhasil disimpan!");
            }
            catch(SQLException ex){
                Logger.getLogger(pelangganView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tambahPelangganActionPerformed

    private void ubahPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahPelangganActionPerformed
        // TODO add your handling code here:
        String cekkodePelanggan = kodePelanggan.getText();
        
        if(cekkodePelanggan.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data pelanggan yang ingin diubah!");
        }else{
            try{
                pelanggan plg = new pelanggan();
                plg.setkodePelanggan(kodePelanggan.getText());
                plg.setNamaPelanggan(namaPelanggan.getText());
                plg.setjenisKelamin((String) jenisKelamin.getSelectedItem());
                plg.setAlamat(alamat.getText());
                plg.setTelp(telp.getText());
                plgServis.update(plg);
                this.statusAwal();
                JOptionPane.showMessageDialog(this, "Data pelanggan berhasil diubah!");
            }
            catch(SQLException ex){
                Logger.getLogger(pelangganView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_ubahPelangganActionPerformed

    private void hapusPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPelangganActionPerformed
        // TODO add your handling code here:
        String cekkodePelanggan = kodePelanggan.getText();
        
        if(cekkodePelanggan.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data pelanggan yang ingin dihapus!");
        }else{
            try{
                pelanggan plg = new pelanggan();
                String Kode_Pelanggan = kodePelanggan.getText();
                plgServis.delete(Kode_Pelanggan);
                this.statusAwal();
                JOptionPane.showMessageDialog(this, "Data pelanggan berhasil dihapus!");
            }
            catch(SQLException ex){
                Logger.getLogger(pelangganView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_hapusPelangganActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        kosongkanText();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelangganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelangganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelangganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelangganView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelangganView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton hapusPelanggan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jenisKelamin;
    private javax.swing.JTextField kodePelanggan;
    private javax.swing.JTextField namaPelanggan;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JButton tambahPelanggan;
    private javax.swing.JTextField telp;
    private javax.swing.JButton ubahPelanggan;
    // End of variables declaration//GEN-END:variables
}
